### Google

GET http://www.octopusjjb.ovh//users

### Youtube

GET http://localhost:3000/pages


### Connexion

POST http://www.octopusjjb.ovh//connexion


### inscriptions
POST http://www.octopusjjb.ovh/cours/inscription/

### participants
POST http://www.octopusjjb.ovh/cours/inscription/participants

### cours
GET http://www.octopusjjb.ovh/cours/

### cours
POST http://www.octopusjjb.ovh/informations/

### compte
GET http://www.octopusjjb.ovh/compte/